project:
  type: website
  output-dir: docs

website:
  title: "IMSI Movement Science Course"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pathways.qmd
      - all_modules.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com
      - icon: youtube
        href: https://www.youtube.com/@IntegrativeMovementScience
      - icon: instagram
        href: https://www.instagram.com/integrative.movement.science/ 
      - icon: linkedin
        href: https://www.linkedin.com/company/integrative-movement-sciences-institute/
      - text: bluesky
        href: https://bsky.app/profile/movementscience.bsky.social
      
    
      
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.md

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

